import { IAdvertisementMini } from "@/store/@types/advertisement";

const advertisement: IAdvertisementMini[] = [
  {
    name: "Spotify",
    mail: "team@spotify.com",
    duration: "1 month",
    projected_reach: "7,000 users",
    reach: "5000/7000",
    cost: "N12,000",
    status: "Running",
  },
  {
    name: "Airtel",
    mail: "team@airtel.com",
    duration: "2 month",
    projected_reach: "7,000 users",
    reach: "5000/7000",
    cost: "N12,000",
    status: "Running",
  },
  {
    name: "Youtube",
    mail: "team@youtube.com",
    duration: "2 month",
    projected_reach: "7,000 users",
    reach: "5000/7000",
    cost: "N12,000",
    status: "Running",
  },
  {
    name: "Spotify",
    mail: "team@spotify.com",
    duration: "1 month",
    projected_reach: "7,000 users",
    reach: "5000/7000",
    cost: "N12,000",
    status: "Running",
  },
  {
    name: "Airtel",
    mail: "team@airtel.com",
    duration: "2 month",
    projected_reach: "7,000 users",
    reach: "5000/7000",
    cost: "N12,000",
    status: "Running",
  },
  {
    name: "Youtube",
    mail: "team@youtube.com",
    duration: "2 month",
    projected_reach: "7,000 users",
    reach: "5000/7000",
    cost: "N12,000",
    status: "Running",
  },
  {
    name: "Spotify",
    mail: "team@spotify.com",
    duration: "1 month",
    projected_reach: "7,000 users",
    reach: "5000/7000",
    cost: "N12,000",
    status: "Running",
  },
  {
    name: "Airtel",
    mail: "team@airtel.com",
    duration: "2 month",
    projected_reach: "7,000 users",
    reach: "5000/7000",
    cost: "N12,000",
    status: "Running",
  },
  {
    name: "Youtube",
    mail: "team@youtube.com",
    duration: "2 month",
    projected_reach: "7,000 users",
    reach: "5000/7000",
    cost: "N12,000",
    status: "Running",
  },
  {
    name: "Spotify",
    mail: "team@spotify.com",
    duration: "1 month",
    projected_reach: "7,000 users",
    reach: "5000/7000",
    cost: "N12,000",
    status: "Running",
  },
  {
    name: "Airtel",
    mail: "team@airtel.com",
    duration: "2 month",
    projected_reach: "7,000 users",
    reach: "5000/7000",
    cost: "N12,000",
    status: "Running",
  },
  {
    name: "Youtube",
    mail: "team@youtube.com",
    duration: "2 month",
    projected_reach: "7,000 users",
    reach: "5000/7000",
    cost: "N12,000",
    status: "Running",
  },
  {
    name: "Spotify",
    mail: "team@spotify.com",
    duration: "1 month",
    projected_reach: "7,000 users",
    reach: "5000/7000",
    cost: "N12,000",
    status: "Running",
  },
  {
    name: "Airtel",
    mail: "team@airtel.com",
    duration: "2 month",
    projected_reach: "7,000 users",
    reach: "5000/7000",
    cost: "N12,000",
    status: "Running",
  },
  {
    name: "Youtube",
    mail: "team@youtube.com",
    duration: "2 month",
    projected_reach: "7,000 users",
    reach: "5000/7000",
    cost: "N12,000",
    status: "Running",
  },
];

export default advertisement;
