import React from 'react'
import Head from 'next/head'

type Props = { children: React.ReactNode }

export default function PageLayout({ children }: Props) {
  return (
    <React.Fragment>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/imgs/favicon.png" />
      </Head>

      {children}
    </React.Fragment>
  )
}